{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trackhound.fullname" . }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  GMAIL_CLIENT_ID: {{ .Values.secrets.gmailClientId | quote }}
  GMAIL_CLIENT_SECRET: {{ .Values.secrets.gmailClientSecret | quote }}
  GMAIL_REFRESH_TOKEN: {{ .Values.secrets.gmailRefreshToken | quote }}
  TRACK17_SECURITY_KEY: {{ .Values.secrets.track17SecurityKey | quote }}
{{- end }}
